const defaultSites = {
    'Algemeen Dagblad': 'ad.nl',
    'Baltimore Sun': 'baltimoresun.com',
    'Barron\'s': 'barrons.com',
    'Bloomberg': 'bloomberg.com',
    'Bloomberg Quint': 'bloombergquint.com',
    'Business Insider': 'businessinsider.com',
    'Caixin': 'caixinglobal.com',
    'Chemical & Engineering News': 'cen.acs.org',
    'Chicago Tribune': 'chicagotribune.com',
    'Central Western Daily': 'centralwesterndaily.com.au',
    'Crain\'s Chicago Business': 'chicagobusiness.com',
    'Corriere Della Sera': 'corriere.it',
    'Daily Press': 'dailypress.com',
    'DeMorgen': 'demorgen.be',
    'Denver Post': 'denverpost.com',
    'De Tijd': 'tijd.be',
    'De Groene Amsterdammer': 'groene.nl',
    'de Volkskrant': 'volkskrant.nl',
    'ET Prime': 'prime.economictimes.indiatimes.com',
    'The Economist': 'economist.com',
    'Eindhovens Dagblad': 'ed.nl',
    'Examiner': 'examiner.com.au',
    'Financial Times': 'ft.com',
    'Foreign Policy': 'foreignpolicy.com',
    'Fortune': 'fortune.com',
    'Glassdoor': 'glassdoor.com',
    'Haaretz': 'haaretz.co.il',
    'Haaretz English': 'haaretz.com',
    'Handelsblatt': 'handelsblatt.com',
    'Harper\'s Magazine': 'harpers.org',
    'Hartford Courant': 'courant.com',
    'Harvard Business Review': 'hbr.org',
    'Inc.com': 'inc.com',
    'Investors Chronicle': 'investorschronicle.co.uk',
    'La Repubblica': 'repubblica.it',
    'La Stampa': 'lastampa.it',
    'Le Monde': 'lemonde.fr',
    'Le Parisien': 'leparisien.fr',
    'London Review of Books': 'lrb.co.uk',
    'Los Angeles Times': 'latimes.com',
    'Medium': 'medium.com',
    'Medscape': 'medscape.com',
    'MIT Technology Review': 'technologyreview.com',
    'Mountain View Voice': 'mv-voice.com',
    'National Post': 'nationalpost.com',
    'New Statesman': 'newstatesman.com',
    'New York Magazine': 'nymag.com',
    'Nikkei Asian Review': 'asia.nikkei.com',
    'NRC': 'nrc.nl',
    'New Zealand Herald': 'nzherald.co.nz',
    'Orange County Register': 'ocregister.com',
    'Orlando Sentinel': 'orlandosentinel.com',
    'Palo Alto Online': 'paloaltoonline.com',
    'Parool': 'parool.nl',
    'Quartz': 'qz.com',
    'Quora': 'quora.com',
    'Scientific American': 'scientificamerican.com',
    'Statista': 'statista.com',
    'SunSentinel': 'sun-sentinel.com',
    'Tech in Asia': 'techinasia.com',
    'Telegraaf': 'telegraaf.nl',
    'The Advocate': 'theadvocate.com.au',
    'The Age': 'theage.com.au',
    'The Atlantic': 'theatlantic.com',
    'The Athletic': 'theathletic.com',
    'The Australian': 'theaustralian.com.au',
    'The Australian Financial Review': 'afr.com',
    'The Boston Globe': 'bostonglobe.com',
    'The Business Journals': 'bizjournals.com',
    'The Daily Telegraph': 'dailytelegraph.com.au',
    'The Diplomat': 'thediplomat.com',
    'The Globe and Mail': 'theglobeandmail.com',
    'The Herald': 'theherald.com.au',
    'The Hindu': 'thehindu.com',
    'The Japan Times': 'japantimes.co.jp',
    'TheMarker': 'themarker.com',
    'The Mercury Tasmania': 'themercury.com.au',
    'The Mercury News': 'mercurynews.com',
    'The Morning Call': 'mcall.com',
    'The Nation': 'thenation.com',
    'The New York Times': 'nytimes.com',
    'The New Yorker': 'newyorker.com',
    'The News-Gazette': 'news-gazette.com',
    'The Philadelphia Inquirer': 'inquirer.com',
    'The Saturday Paper': 'thesaturdaypaper.com.au',
    'The Spectator': 'spectator.co.uk',
    'The Seattle Times': 'seattletimes.com',
    'The Sydney Morning Herald': 'smh.com.au',
    'The Telegraph': 'telegraph.co.uk',  
    'The Times': 'thetimes.co.uk',
    'The Toronto Star': 'thestar.com',
    'The Washington Post': 'washingtonpost.com',
    'The Wall Street Journal': 'wsj.com',
    'Times Literary Supplement': 'the-tls.co.uk',
    'Towards Data Science': 'towardsdatascience.com',
    'Trouw': 'trouw.nl',
    'Vanity Fair': 'vanityfair.com',
    'Vrij Nederland': 'vn.nl',
    'Wired': 'wired.com',
    '*General Paywall Bypass*': 'generalpaywallbypass',
  };
